name: CI

on:
  push:
    branches: [ aarch64 ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set Env
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: |
          linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/openvpn:${{ env.DATE }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/openvpn:latest
    - name: Build and push armv7
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.armv7
        platforms: |
          linux/arm/v7
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/openvpn:armv7-${{ env.DATE }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/openvpn:armv7-latest
    - name: Build and push armv6
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.armv6
        platforms: |
          linux/arm/v6
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/openvpn:armv6-${{ env.DATE }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/openvpn:armv6-latest
